server:
  port: 8000

spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  cloud:
    function:
      definition: paymentStatusUpdate;processOrderEvent
    stream:
      bindings:
        paymentStatusUpdate-in-0:
          destination: arka.events.payment-status-update
          group: msvc-notification-group
          content-type: application/json
          binder: rabbit

        processOrderEvent-in-0:
          destination: order-status-events
          group: msvc-notification-group
          content-type: application/json
          binder: rabbit

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
