spring:
  application:
    name: msvc-orders

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:orderdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:100juanU}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  cloud:
    stream:
      bindings:
        orderStatusUpdate-out-0:
          destination: order-status-events
          content-type: application/json
          binder: rabbit

server:
  port: ${PORT:8082}

logging:
  level:
    com.springcloud.msvc_orders: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
