server:
  port: ${PORT:8086}

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:cartdb}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:100juanU}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}

logging:
  level:
    com.springcloud.msvc_carts.infrastructure.integration.client.OrderFeignClient: DEBUG
