spring:
  application:
    name: msvc-payments

  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:paydb}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:100juanU}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

  rabbitmq:
    host: ${RABBITMQ_HOST:rabbitmq}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USER:guest}
    password: ${RABBITMQ_PASS:guest}

  cloud:
    openfeign:
      okhttp:
        enabled: true
    stream:
      bindings:
        paymentStatusUpdate-out-0:
          destination: arka.events.payment-status-update
          content-type: application/json
          binder: rabbit
      functions:
        paymentStatusUpdate: paymentStatusUpdate

server:
  port: ${SERVER_PORT:8087}

logging:
  level:
    com.springcloud.msvc_payments: DEBUG

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
